services:
  - type: web
    name: dorayama-seizo-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DORAYAMA_SA_CRED_JSON
        sync: false
